# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vue.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_vue:
    name: Build Vue App
    steps:
      runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15
      uses: actions/setup-node@v1
      with: 
        node-version: 14.15
      - run: npm i
      - run: npm run test
