# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vue.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Run Tests Vue App
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - name: npm i to install everything
      - run: npm ci
      - name: Run our tests with npm run test:unit
      - run: npm run test:unit

    name: Build And Deploy Vue App
    steps:
      - name: Build our Vue app
      - run: npm run build
